import Head from 'next/head'
import styles from '../styles/Home.module.css'
import NavBar from "../components/NavBar"
import HeroSection from "../components/HeroSection"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kannan Palani</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar />
        <HeroSection />


      </main>

      
    </div>
  )
}
